spring.application.name=EcommerceBackendProject
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_dev
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
upload.dir=updated/photos
jwt.secret=doyourjumpssonnobodyyesdoorthedadisawesomethereisnoway
jwt.expiration=36000000